### ISSUE TITLE
No such file or directory: 'Xvfb'

### ISSUE THREAD

**Issue by jmbeach** [mwleeds/MyBamaChecker#1]
I'm trying to run the grade checker. The full terminal output is: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/easyprocess/__init__.py", line 225, in start
    env=self.env,
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/easyprocess/__init__.py", line 178, in check_installed
    self.call()
  File "/usr/local/lib/python3.5/site-packages/easyprocess/__init__.py", line 194, in call
    self.start().wait(timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/easyprocess/__init__.py", line 230, in start
    raise EasyProcessError(self, 'start error')
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help'] cmd=['Xvfb', '-help'] oserror=[Errno 2] No such file or directory: 'Xvfb' returncode=None stdout="None" stderr="None" timeout=False>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "CheckGrades.py", line 22, in <module>
    main()
  File "CheckGrades.py", line 12, in main
    crawler = MyBamaChecker(True)
  File "/Users/jbeach/Code/Sandbox/MyBamaChecker/MyBamaChecker.py", line 29, in __init__
    Display(visible=0, size=(2000, 1600)).start()
  File "/usr/local/lib/python3.5/site-packages/pyvirtualdisplay/display.py", line 33, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python3.5/site-packages/pyvirtualdisplay/display.py", line 51, in display_class
    cls.check_installed()
  File "/usr/local/lib/python3.5/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python3.5/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory: 'Xvfb'
Program install error! 
Exception ignored in: <bound method MyBamaChecker.__del__ of <MyBamaChecker.MyBamaChecker object at 0x1066944e0>>
Traceback (most recent call last):
  File "/Users/jbeach/Code/Sandbox/MyBamaChecker/MyBamaChecker.py", line 280, in __del__
AttributeError: 'MyBamaChecker' object has no attribute 'driver'
```

I'm on a 64 bit Mac running El Capitan. 

I think the problem is that I don't have X11. [This Stackoverflow post](http://stackoverflow.com/questions/25451133/xvfb-run-on-os-x) says to install [XQuartz](https://www.xquartz.org/), so I'm working on that now.

**Comment by jmbeach** [comment]
Installing XQuartz and restarting solved it.
